### PR TITLE
Final version with team5

### PR DESCRIPTION
**Pull request by Weeblin**

### CODE REVIEW

**Comment by antonypap** [comment]
Make sure to also add your team's agent in the `.env` file

**Comment by Weeblin** [comment]
> Make sure to also add your team's agent in the `.env` file

Thaks, how many agents should we instantiate btw?

**Comment by antonypap** [comment]
> > Make sure to also add your team's agent in the `.env` file
> 
> Thanks, how many agents should we instantiate btw?

That's a good question, that's also a parameter for testing so don't think there is a "correct" answer to that.

**Comment by TIE666** [comment]
> > > Make sure to also add your team's agent in the `.env` file
> > 
> > 
> > Thanks, how many agents should we instantiate btw?
> 
> That's a good question, that's also a parameter for testing so don't think there is a "correct" answer to that.

I will just add the line there with 30 for now (for each 3 teams currently)

**Review by antonypap — APPROVED** [review]

**Review by TIE666 — APPROVED** [review]

**Pull request merged**
