### PR TITLE
Globally accessible copies of game config

### PR DESCRIPTION
**Pull request by Razvan00Rusu**
At the moment the game config is passed around to functions as a parameter. I think it is cleaner if we keep one `config` object and then create copies when required. 

Also useful because these values might (and probably will) be needed in all over code and might be hard to get the values where they're needed.

Conversely, this would allow agents to see these values which may/may not be wanted!?

### CODE REVIEW

**Comment by Razvan00Rusu** [comment]
Oops, doing 2 PRs at once and seem to have lost a commit somewhere - 1 sec.

**Comment by neeldug** [comment]
Agents can currently change the global config from this using init which probably should be hidden somehow...

**Comment by Razvan00Rusu** [comment]
> Agents can currently change the global config from this using init which probably should be hidden somehow...
> 
> While I do think this is a good change, it should probably still hide a lot from the agent teams.

That's what the guard  clause at the start of the init function is for - as far as I can tell the config can only be initialised once because config.Initialised will be stuck as `true` no?

**Comment by neeldug** [comment]
> That's what the guard clause at the start of the init function is for - as far as I can tell the config can only be initialised once because config.Initialised will be stuck as `true` no?

Ah okay, but can't they change it during their constructor, since that's called prior?

**Comment by Razvan00Rusu** [comment]
> > That's what the guard clause at the start of the init function is for - as far as I can tell the config can only be initialised once because config.Initialised will be stuck as `true` no?
> 
> Ah okay, but can't they change it during their constructor, since that's called prior?

Ah yes that is a very valid point you raise.

**Comment by Razvan00Rusu** [comment]
> > That's what the guard clause at the start of the init function is for - as far as I can tell the config can only be initialised once because config.Initialised will be stuck as `true` no?
> 
> Ah okay, but can't they change it during their constructor, since that's called prior?

Yeah so can confirm that agents can initialise the config

> > That's what the guard clause at the start of the init function is for - as far as I can tell the config can only be initialised once because config.Initialised will be stuck as `true` no?
> 
> Ah okay, but can't they change it during their constructor, since that's called prior?

A bit of reshuffling but from my own experiments my latest commit stops this from happening by delaying the agent constructor calls until after the game config is created. I **think** I've used `defer` correctly on `instantiateAgent` and it seems to be working fine when I run it....👀

The issue of not everything being available to agents is similar to #68 and a choice should be made soon so agent teams know what is available.

**Pull request closed without merging**
