### PR TITLE
[BugFix] Subtract Total Attack/Defense from Stamina

### PR DESCRIPTION
**Pull request by antonypap**
BugFix #174

### CODE REVIEW

**Comment by neeldug** [comment]
When we, (@Razvan00Rusu and I) initially talked with @BusterBlack regarding this issue, it seemed like this was the intended behaviour, is this incorrect now?

**Comment by antonypap** [comment]
> When we, (@Razvan00Rusu and I) initially talked with @BusterBlack regarding this issue, it seemed like this was the intended behaviour, is this incorrect now?

Without any loot allocation or if everyone was forced to Defend according to the social contract that could result in a never ending fight...

**Comment by BusterBlack** [comment]
Yes we did say that `agentState.Stamina -= agentState.BonusAttack` ..... Now that i think about it with inventories in mind. I think that it should be changed to `agentState.Stamina -= agentState.TotalAttack`... Shouldn't make any differences to the game.

**Review by neeldug — APPROVED** [review]
LGTM

**Pull request merged**
