### PR TITLE
Team 6 Agent

### PR DESCRIPTION
**Pull request by Razvan00Rusu**

### CODE REVIEW

**Comment by thl19git** [comment]
Looking at the failing check, I guess it is possible an agent could receive a proposal before generating their own - could do proposal generation right at the start??

**Comment by Razvan00Rusu** [comment]
> Looking at the failing check, I guess it is possible an agent could receive a proposal before generating their own - could do proposal generation right at the start??

I thought this was just because the in team6_similarity.go the ToSinglePredicate method can return nil if there aren't any predicates - causing the nil pointer dereference when this function is tried to be called. I added a default action that should hopefully fix this issue - lets wait for the latest tests.

**Comment by Razvan00Rusu** [comment]
Welp it failed again - i have absolutely no idea what is causing this one... :////

**Comment by thl19git** [comment]
> Welp it failed again - i have absolutely no idea what is causing this one... :////

The log is pretty useless :(

**Comment by Razvan00Rusu** [comment]
> > Welp it failed again - i have absolutely no idea what is causing this one... :////
> 
> The log is pretty useless :(

if agent performance ones pass - idk how long theyll take, i say we gamble and just merge in anyway.

**Comment by thl19git** [comment]
> > > Welp it failed again - i have absolutely no idea what is causing this one... :////
> > 
> > 
> > The log is pretty useless :(
> 
> if agent performance ones pass - idk how long theyll take, i say we gamble and just merge in anyway.

Both look to be stuck :/

**Comment by Razvan00Rusu** [comment]
> > > > Welp it failed again - i have absolutely no idea what is causing this one... :////
> > > 
> > > 
> > > The log is pretty useless :(
> > 
> > 
> > if agent performance ones pass - idk how long theyll take, i say we gamble and just merge in anyway.
> 
> Both look to be stuck :/

I am a firm believer in gambling with merges 👀. The game does run fine locally at least - might be something a bit wonky with the CI.

**Review by thl19git — APPROVED** [review]

**Pull request merged**
