### PR TITLE
Revert "agent 4 demo code added"

### PR DESCRIPTION
**Pull request by antonypap**
Reverts SOMAS2022/SOMAS2022#193 (breaking actions)

### CODE REVIEW

**Review by BusterBlack — APPROVED** [review]
yep. The dead-lock is from a previous commit... check #186... but i don't think they could find the issue....

**Comment by antonypap** [comment]
But then again, #189 seems to pass all the tests somehow...?

**Comment by BusterBlack** [comment]
> But then again, #189 seems to pass all the tests somehow...?

i don't think that it did..... it failed the same test (no.1)

**Comment by antonypap** [comment]
K will merge it for now

**Pull request merged**
