### PR TITLE
Final Version: Team2 - Agent2

### PR DESCRIPTION
**Pull request by vasilissoti**
Co-Authored-By: Giorgos Vyronos <59888927+giorgosvyronos@users.noreply.github.com>
Co-Authored-By: mitgit19 <59966819+mitgit19@users.noreply.github.com>
Co-Authored-By: Poulpinkk <82034589+Poulpinkk@users.noreply.github.com>
Co-Authored-By: nickilioudis <60299624+nickilioudis@users.noreply.github.com>

### CODE REVIEW

**Comment by vasilissoti** [comment]
After numerous debugging attempts we can now ensure that our agent with the current infrastructure and team 1 agent are successfully passing all tests.

**Comment by vasilissoti** [comment]
In the next test, we will be testing with all remaining agents (i.e 3,4,5,6).

**Comment by vasilissoti** [comment]
Based on the results from above and the previous test run we can deduce that the addition of the other agents leads to an error in both the deadlock and the the test coverage / data-race. The only reasonable explanation that we can give is that after a certain point the presence of all 6 agents makes the game too computationally intense leading to failing tests.

Important!: We can ensure that the code runs locally with all 6 agents as in the latest commit.

**Review by giorgosvyronos — APPROVED** [review]
Merging based on findings and comments in PR: https://github.com/SOMAS2022/SOMAS2022/pull/203

**Pull request merged**
