### PR TITLE
[infra] P2P messaging

### PR DESCRIPTION
**Pull request by neeldug**
Adds support for P2P messaging, safely

### CODE REVIEW

**Review by Razvan00Rusu — APPROVED** [review]
🚀

**Comment by 0x6770** [comment]
Has this PR implement timeout for p2p communication?

**Comment by Razvan00Rusu** [comment]
> Has this PR implement timeout for p2p communication?

AFAIK no, but this PR mainly tackles the trouble of setting up and, non-trivially, tearing down closed channels between agents. The timeout should be just a fairly minor addition on top of this if needed.

**Comment by neeldug** [comment]
> Has this PR implement timeout for p2p communication?

Not yet — there are a few ways to deal with it, we could spawn a go routine on the main thread that submits to the default action provided by the agent on timeout and generate a decision, this does incur a data race problem with regards to users’ implementation of default so might need to be clarified.

**Comment by neeldug** [comment]
This should be easily extendable by genericizing the methods to fight loot and hp pool

**Pull request merged**
