### PR TITLE
fix #12, move Makefile to scripts/

### LINKED ISSUE #12: Project structure
Structure wise (just to keep it as clean and straight-forward as possible), should we put:

- Makefile into the `\scripts` folder  (https://github.com/SOMAS2022/SOMAS2022/pull/8#discussion_r1019216334)
- Executable outputs into the `\cmd` directory
- Teams agent implementations in the `\pkg\agents` directory

### PR DESCRIPTION
**Pull request by 0x6770**
- add go workspace file go.work
- move Makefile to scripts/
- add .gitignore to ignore executables generated

### CODE REVIEW

**Review by Razvan00Rusu — APPROVED** [review]
Looks good to me - I tried everything out, it works and simplifies the process a lot so have no problem merging this in. 

However, I personally think that it is more intuitive for the Makefile to be in the root directory contrary to #12. Happy to drop this matter if people disagree with me though : )

**Comment by 0x6770** [comment]
> Looks good to me - I tried everything out, it works and simplifies the process a lot so have no problem merging this in.
> 
> However, I personally think that it is more intuitive for the Makefile to be in the root directory contrary to #12. Happy to drop this matter if people disagree with me though : )

I agree, move Makefile to `scripts/` introduces some confusing pieces to this file, e.g. need to use `cd` in most targets. root is probably a better place for it.

**Review by neeldug — APPROVED** [review]
LGTM

**Review by Razvan00Rusu — APPROVED** [review]
All good!

**Comment by antonypap** [comment]
Ok yeah I guess that this works as well, makes it much more intuitive for everyone

**Review by antonypap — APPROVED** [review]

**Pull request merged**
