### PR TITLE
Revert "[infra] Create API for individual team use"

### PR DESCRIPTION
**Pull request by Razvan00Rusu**
Reverts SOMAS2022/SOMAS2022#39

Opening this revert PR because there is a bit of confusion about the use case for the changes made here - especially in `infra/stages/stages.go`.

Can we get more clarification / an example on how this would be used and how it fits in the bigger picture?

### CODE REVIEW

**Comment by sherwin-dc** [comment]
Mostly it is about changing current rules for team experiments, though I cant image all the possibilities just yet. If I were to add the function that initialises agents into `stages`, different agents could be made to start out with different stats. A different agent strategy map could also be placed within the team's files, which is needed for team experiments.

I think we wont know just yet what else is possible until the infra code for HP pool, resource allocation and peer trading is written.  Though this should allow for the default behaviour in those areas could be changed. If we wanted to we could even have players attack each other during trading and get others equipment for example.

**Comment by 0x6770** [comment]
> Mostly it is about changing current rules for team experiments, though I cant image all the possibilities just yet. If I were to add the function that initialises agents into `stages`, different agents could be made to start out with different stats. A different agent strategy map could also be placed within the team's files, which is needed for team experiments.
> 
> I think we wont know just yet what else is possible until the infra code for HP pool, resource allocation and peer trading is written. Though this should allow for the default behaviour in those areas could be changed. If we wanted to we could even have players attack each other during trading and get others equipment for example.

I see your point and agree this plug and play capability is valuable as it allows teams to experiment with more interesting game rules. However I'm a bit worried because this means teams may end up with divergence in game rules, each agent being optimised in their own "world". Not sure if this is a problem or if we want to allow this.

**Comment by sherwin-dc** [comment]
> > Mostly it is about changing current rules for team experiments, though I cant image all the possibilities just yet. If I were to add the function that initialises agents into `stages`, different agents could be made to start out with different stats. A different agent strategy map could also be placed within the team's files, which is needed for team experiments.
> > I think we wont know just yet what else is possible until the infra code for HP pool, resource allocation and peer trading is written. Though this should allow for the default behaviour in those areas could be changed. If we wanted to we could even have players attack each other during trading and get others equipment for example.
> 
> I see your point and agree this plug and play capability is valuable as it allows teams to experiment with more interesting game rules. However I'm a bit worried because this means teams may end up with divergence in game rules, each agent being optimised in their own "world". Not sure if this is a problem or if we want to allow this.

I think either way teams would need to create agents that play against other agents within the normal rules. I think it will depend on how much teams are able to differentiate agents from the rest, assuming each team creates one agent.

But if its too early in to know yet we could just leave this PR for now till we know more or get feedback from others.

**Review by neeldug — APPROVED** [review]
LGTM -- need to revert briefly for p2p to work, signature changes causing difficulty in merging

**Pull request merged**
