### PR TITLE
[infra] Loot allocation

### LINKED ISSUE #72: [infra] loot allocation design
I assume the current implementation of loot allocation is just as a placeholder. We can use this issue to plan out the design of actual loot allocation. 

If this has not been decided, perhaps we can start with the questions below,
1. What types of item can we get in the loot (and store in inventory)? 
   Currently we have potion for health point, shield for defense point and weapon for attack point, do we want items with a mix of HP, DP and AP? 
2. How many items of potion/weapon/shield can each agent have at the same time?
   From #68, it seems like each agent will have at least 2 items for each type. One visible to the public, the rest is stored in the inventory and is not visible to others. 
3. Or maybe we do not limit the number of item of specific type that a agent can hold, but limit the capacity of inventory so $n \ge \text{size}(\text{shields}) + \text{size}(\text{potions}) + \text{size}(\text{weapon})$ 
4. AS discussed in #38 , we probably want the value of these items to be quantised or integer based.
5. How do we allocate the loot? 
   Do we broadcast all available loot to all agents, let them choose want they want and randomly pick a winner if conflict happens? 
   If agent A and agent B both want `item 1`, and A get `item 1` eventually, will B have the chance to ask a new item?
   OR, do we adapt the voting based weighted allocation mentioned in the lecture? 
6. What kind of power do we want the leader to have over loot allocation? 
   Maybe we can let leader to solve conflict?

### PR DESCRIPTION
**Pull request by neeldug**
- Adds initial loot allocation feature
- Adds imposition/proposal based solutions
- Pushes loot pool outside of global state
- Adds multi predicate (multiple items per agent)

Fixes #72

### CODE REVIEW

**Comment by 0x6770** [comment]
Nice work! It would be great if you could add some comments to your code, or describe your how the current implementation of loot allocation work, a brief outline will be perfect. This will make it easier for other people to understand and use your code.

**Review by Weeblin — APPROVED** [review]
LGTM

**Comment by neeldug** [comment]
> Nice work! It would be great if you could add some comments to your code, or describe your how the current implementation of loot allocation work, a brief outline will be perfect. This will make it easier for other people to understand and use your code.

Yeah — I can understand that but for the most part it essentially duplicates fight rounds with the adjustment that proposals dictate who can get which type of item, not the quality, and from that set the infrastructure decides specifics using some utility score (todo) or randomly (currently done), this then produces a provisional allocation which is currently enforced but we could add it such that agents receive their provisional allocation and then can respond back with their chosen allocation whereby we resolve conflicts.

The rest of the code changes follow on simply from the fight logic, potions are no longer stored in global state and I think having done this change we should detach BonusAttack and BonusDefence from state (such that other agents can see this stat anyway).

**Review by Razvan00Rusu — APPROVED** [review]
Let's Gamble, Try Merge 🚀

**Pull request merged**
